### PR TITLE
Release v 1.0

### PR DESCRIPTION
**Pull request by mekinus**
Release version 1.0.0

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi @mekinus 
It`s a pity but This Code Review Request will be marked as invalid, so please submit a new one once you are ready!


- [x]  You should use Github/Git Flow in this project. Please take a step back and watch video here [Using GitHub Flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). Then create a brand new repo with correct setup and feature branch (with DESCRIPTIVE name) and copy your code there or close this pull request and create another one with correct feature branch . 


  - [x] Please add descriptive README file

Screenshot from 2019-11-29 02-14-15
  - [x] Add meaningful title and short summary for your next Pull Requests

**Comment by mekinus** [comment]
> ### Hi @mekinus
> It`s a pity but This Code Review Request will be marked as invalid, so please submit a new one once you are ready!
> 
> https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/github_flow_requirement.png
> 
> * You should use Github/Git Flow in this project. Please take a step back and watch video here [Using GitHub Flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). Then create a brand new repo with correct setup and feature branch (with DESCRIPTIVE name) and copy your code there or close this pull request and create another one with correct feature branch .
> * Please add descriptive README file
> 
> https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png
> 
> * Add meaningful title and short summary for your next Pull Requests

I worked on the developer (feature-branch) on this repo, using the same git flow i learn and did with all my previous projects, the descriptive readme is already updated on the master branch.

**Comment by mekinus** [comment]
@Anna-Myzukina i am kindly waiting for your reply before i submit my code again =)

**Comment by Anna-Myzukina** [comment]
@mekinus kindly recommended to use Github/Git Flow in this project. Please take a step back and watch video here [Using GitHub Flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). Then create a brand new repo with correct setup and feature branch (with DESCRIPTIVE name) and copy your code there or close this pull request and create another one with correct feature branch . 

> @Anna-Myzukina i am kindly waiting for your reply before i submit my code again =)

Branches should have descriptive name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section').

**Comment by mekinus** [comment]
@Anna-Myzukina 

**"We assume that this entire project is one feature for learning purposes "** 
i quoted this Microverse project description guide and this is why i made only one feature branch named developer branch :)

And this is what i have done with all my previous projects and my partner @TashfeenRAO did for his project and got approved. , i am confused now, help me to clear my mind.

**Comment by Anna-Myzukina** [comment]
> @Anna-Myzukina
> 
> "We assume that this entire project is one feature for learning purposes " i quoted this Microverse project description guide and this is why i made only one feature branch named developer branch :)
> 
> And this is what i have done with all my previous projects and my partner @TashfeenRao did for his project and got approved. , i am confused now, help me to clear my mind.

If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.

**Comment by trox115** [comment]
### This project is under review by António Fernandes

**Comment by trox115** [comment]
### Status: Changes Required
Hello @mekinus, it's very nice to meet you :handshake: . You have done a good job until now. However in order to approve your project, you need to make some changes. 

The font on the date it's too small. You can decrease the size of the font and increase the size of the header, so it looks more like the original. 

The 'FEATURED STORIES' and ' Top Stories' have the same width. If you look at the original, they have different widths.

 

Also, you have too much margin left and right on the container. Try maybe the [container-fluid](https://getbootstrap.com/docs/3.4/css/) . 

You need to correct this little bug too, otherwise your site looks bad, and nothing like the original . 
. 


**Summary**
- [ ]  Decrease the margin from the main-content
- [ ]  Change date size
- [ ]  Change column Top stories width
- [ ]  Address to the column sizes from the US section until the footer.


You doing great, keep it up. Anything that you need you can ask me on Slack. 
**You Got This** :muscle: :sunglasses:

**Review by izaiasneto4 — CHANGES_REQUESTED** [review]
### Hello @mekinus nice work fixing the requested changes so far :+1: . We need to fix a few more things to get your project approved :arrow_down: 

- [x] Decrease the margin between the columns "Top Story" and "Featured Stories" to make it look like the original website
- [x] Try to not leave blank spaces in the page, there wasn't supposed to be a big gap between the middle column and the rest of the content in the website
- [x] You have some images that seem to be stretched and out of proportion, let's fix those.
- [ ] When reducing the size of the screen to test responsiveness, I've noticed that your right-most column overlaps the "Top Story" column. Let's fix that. 
- [ ] When reducing the size of the screen to test responsiveness, I've noticed that your right-most column overlaps the "Top Story" column. Let's fix that.
Screenshot from 2019-12-04 15-56-02

#### When finished with these changes, please submit the project for a new review :pray:

**Comment by shshamim63** [comment]
## Status :recycle: [Changes Required] :recycle: 
___
Hi @mekinus :wave: ,
Awesome job :clap: . I can see you have gathered all the items that are actually needed to decorate the page. And you have tried to cover the issues raised by previous reviewer. I have found some additional issues that are also needed to cover. So that this project look exactly as the original one. And I am sure that you will cover them easily :sunglasses: .
___
### :space_invader: [Mandatory Changes] :space_invader: 
___
All the changes are related to Responsive web design.
##### :desktop_computer:  Large Screen View:
1. Culture and travel part is broken. The content are not rendering the defined place.
image
___
##### :computer:  Medium Screen View:
___
1. The navbar is not changing. But on the actual web-page it does.
###### Your one->
image
###### Actual one->
image
2. Your items are collapsing from feature stories to just before opinion section.
image
3. On the actual webpage In the magazine section does not change its layout. But your one is changing.
image
4. The feature slide show should contain equal width. But you one is not taking it.
image
5. US section and the rest similar section are also broken.
image
###### Actual one -> 
image
6. Footer is also broken.
image
___
##### :vibration_mode: Mobile Screen View:
1. Navbar is not changing its view.
image
2. Footer is broken.
image
___
##### Please fix the above mentioned issues and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Review by mosesogwo — APPROVED** [review]
## :+1: You've come a long way with this project.

I salute your determination.

### Your project is approved! :clap: 
You may now merge to master.
Good luck in your next project.

### Status: Approved.

**Comment by mekinus** [comment]
Thanks =)

**Pull request merged**
